
export const images = {
    back: 'back.svg',
    back_w: 'back_w.svg',
    profile: 'profile.svg',
    create: 'create.svg',
    delete: 'delete.svg',
    update: 'update.svg',
    cancel: 'cancel.svg',
    save: 'save.svg',
    passopen: 'passopen.svg',
    passclose: 'passclose.svg',
    menu: 'menu.svg',
    menu_w: 'menu_w.svg',
    updated: 'updated.svg',
    manage: 'manage.svg',
    add: 'add.svg',
    add_blue: 'add_blue.svg',
    logout: 'logout.svg',
    loading: 'loading.svg',
    loading_blue: 'loading_blue.svg',
    nodata: 'nodata.png',
};

export const category = [
    'Billing Issues',
    'Power Outage',
    'Voltage Fluctuation',
    'Meter Malfunction',
    'Delay in Service',
    'Streetlight Fault',
    'Faulty Meter Reading',
    'Transformer Failure',
    'Unauthorized Wiring',
    'High Electricity Bill',
    'Disconnection/Reconnection Issue',
]
